- name: Setup Remi PHP 7 Repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install MySQL, PHP, Git
  yum:
    name:
      - mariadb-server
      - php-fpm
      - php-mysql
      - php-pdo
      - python-pip
      - git
    state: present
    enablerepo: remi-php72
  notify: restart nginx

- name: Start Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - mariadb
    - php-fpm
  notify: restart nginx

- file:
    path: /var/lib/php/session/
    owner: nginx
    group: nginx
    mode: 0777
    state: directory

- name: Install asciidoc packages (RHEL)
  yum:
    name:
      - asciidoc
      - rubygem-asciidoctor
    state: present
    enablerepo: rhui-REGION-rhel-server-optional
  when: ansible_distribution == 'RedHat'

- name: Install asciidoc packages (CentOS)
  yum:
    name:
      - asciidoc
      - rubygem-asciidoctor
    state: present
  when: ansible_distribution == 'CentOS'

- name: Copy lab guides to server
  copy:
    src: docs/lab_guide/
    dest: /usr/share/nginx/html/
  register: copycontent

- name: Build HTML Docs
  command: asciidoc -d book -v -o {{ item }}.html {{ item }}.adoc
  args:
    chdir: /usr/share/nginx/html/
  with_items:
    - index
    - wrapup
    - exercise1
    - exercise2
    - exercise3
    - exercise4
    - exercise5
    - exercise6
    - exercise7
  when: copycontent.changed

- name: Create users directory on server
  file:
    path: /usr/share/nginx/html/users/
    state: directory

- name: Copy users file to server
  template:
    src: templates/index.php.j2
    dest: /usr/share/nginx/html/users/index.php

- name: Copy list file to server
  template:
    src: templates/list.php.j2
    dest: /usr/share/nginx/html/users/list.php

- name: Create deck directory on server
  file:
    path: /usr/share/nginx/html/decks/
    state: directory

- name: Copy deck to server
  copy:
    src: docs/decks/
    dest: /usr/share/nginx/html/decks/

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Create a new database with name 'workshop'
  mysql_db:
    name: workshop
    state: present

- name: Copy SQL template to server
  template:
    src: templates/workshop.sql.j2
    dest: /tmp/workshop.sql
  register: workshopsql

- name: Import SQL file into workshop database
  mysql_db:
    state: import
    name: workshop
    target: /tmp/workshop.sql
  when: workshopsql.changed

- include_tasks: git_lab.yml
  when: git_lab
- include_tasks: adv_lab.yml
  when: advanced_lab
