- name: Install Windows Updates until complete
  hosts: windows_domain_controllers,windows_workstations
  tasks:
    - name: Install Updates
      win_updates:
        reboot: yes
        reboot_timeout: 3600
      register: update_result
      until: update_result.found_update_count == 0 or update_result.failed_update_count == update_result.found_update_count
